version: '3.0'

expectations:
  population_size: 300000

actions:
  vax_eligibility_inputs:
    run: r:latest analysis/vax_eligibility_inputs.R
    outputs:
      highly_sensitive:
        vax_study_dates_json: output/vax_study_dates.json
        vax_jcvi_groups: output/vax_jcvi_groups.csv
        vax_eligible_dates: output/vax_eligible_dates.csv

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format feather
    needs: [vax_eligibility_inputs] 
    outputs:
      highly_sensitive:
        cohort: output/input.feather

  preprocess_data:
    run: r:latest analysis/preprocess_data.R
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        cohort: output/input.rds
        venn: output/venn.rds

  stage1_data_cleaning:
    run: r:latest analysis/Stage1_data_cleaning.R
    needs: [preprocess_data]
    outputs:
      moderately_sensitive:
        QA_rules: output/QA_summary.csv
        refactoring: output/meta_data_factors.csv
        IE_criteria: output/cohort_flow.csv
      highly_sensitive:
        cohort: output/input_stage1.rds

  stage2_missing_table1:
    run: r:latest analysis/Stage2_Missing_Table1.R 
    needs: [stage1_data_cleaning]
    outputs:
      moderately_sensitive:
        Missing_RangeChecks: output/Check_missing_range.csv
        DateChecks: output/Check_dates_range.csv
        Descriptive_Table: output/Table1.csv

  stage3_diabetes_flow:
    run: r:latest analysis/diabetes_flowchart.R
    needs:
    - stage1_data_cleaning
    outputs:
      moderately_sensitive:
        flow_df: output/diabetes_flow_values.csv      
        # flow_fig: output/diabetes_flow.png

  # stage4_table2:
  #   run: r:latest analysis/table_2.R
  #   needs:
  #   - stage1_data_cleaning
  #   outputs:
  #     moderately_sensitive:
  #       table2: output/table2.csv

  stage4_venn_diagram:
    run: r:latest analysis/venn_diagram.R
    needs:
    - preprocess_data
    - stage1_data_cleaning
    outputs:
      moderately_sensitive:
        venn_diagram: output/venn_diagram_*.svg
        venn_diagram_number_check: output/venn_diagram_number_check_*.csv