version: '3.0'

expectations:
  population_size: 300000

actions:
  vax_eligibility_inputs:
    run: r:latest analysis/vax_eligibility_inputs.R
    outputs:
      highly_sensitive:
        vax_study_dates_json: output/vax_study_dates.json
        vax_jcvi_groups: output/vax_jcvi_groups.csv
        vax_eligible_dates: output/vax_eligible_dates.csv

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format feather
    needs: [vax_eligibility_inputs] 
    outputs:
      highly_sensitive:
        cohort: output/input.feather

  preprocess_data:
    run: r:latest analysis/preprocess_data.R
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        cohort: output/input.rds
        venn: output/venn.rds

  stage1_data_cleaning:
    run: r:latest analysis/Stage1_data_cleaning.R
    needs: [preprocess_data]
    outputs:
      moderately_sensitive:
        refactoring: output/meta_data_factors.csv
        QA_rules: output/QA_summary.csv
        IE_criteria: output/cohort_flow.csv
      highly_sensitive:
        cohort: output/dataset_stage1.rds